name: UltraTrader
main: com.thedemgel.ultratrader.UltraTrader
version: 1.1
depend: [Vault]
softdepend: [Citizens]
api-version: 1.13

commands:
   trader:
      aliases: ut
      description: Main UltraTrader command.
      usage: /<command> [subcommand]
      permission-message: You don't have <permission>
   traderadmin:
      aliases: uta
      description: Utility commands I will remove later
      usage: /<command> [subcommand]
   traderlog:
      aliases: utl
      description: Admin command to view player/shop logs.
      usage: /<command> [player/shopid/selected] [subcommand]
   traderplayer:
      aliases: utp
      description: Specific non-trader related player commands.
      usage: /<command> [subcommand]
