commands:
  delete:
    idrequired: ShopID is required.
    idisanumber: ShopID needs to be a number.
    doesnotexist: Shop does not exist with ID {0}.
    notowner: You need to be the Owner to delete a shop.
  toggleop:
    enable: Shops will now ignore your Onwershop or Op status for transactions.
    disable: Shops will not recognize your Ownershop or Op status for transactions.
conversation:
  abandon: Conversation abandoned.
  admin:
    bankmenu:
      balance: 'Wallet Balance: {0}'
      deposit: deposit
      settype: settype
      type: 'Wallet Type: {0}'
      withdraw: withdraw
    remote:
      enable: Shop remove access enabled.
      disable: Shop remove access disabled.
      nofunds: Insufficient Funds.
      deny: You can't enable remote access.
      prompt:
        enable: Enable Remote Item access for {0}?
        disable: Disable Remote Item access?
    wallet:
      bank:
        choosebank: What Bank do you want to use?
        noaccess: You don't have access to that bank.
        settingbank: Setting bank account.
      player:
        set:
          yourself: Setting wallet to yourself.
    banktypemenu: Choose which type of bank to use.
    begin: Entering Shop Administration Menu
    deposit: How much would you like to Deposit?
    exit: Leaving Admin
    inventorytypemenu: What type of inventory would you like?
    level:
      options:
        decrease: decrease
        increase: increase
        set: set
      proceed: It will cost {0} to goto level {1}, proceed?
      notenoughfunds: You don't have enough funds.
      raised: Level raised to {0}.
      lowered: Level lowered to {0}.
    menu:
      options:
        bank: bank
        exit: exit
        inventoryinterface: inventory
        level: level
        storename: storename
        transfer: transfer
    menutext: CitiTraders Admin Menu
    playerwallet:
      options:
        anotherplayer: another
        yourself: yourself
    prefix: ADMIN
    setbank: Setting bank to
    setinventory: Setting inventory to
    setname:
      nametolong: Shop names can only be 32 characters or shorter.
      setname: Name your shop. (32 Characters Max)
    transfer:
      needstobeonline: (Player needs to be online)
      playercantaccept: Player can't accept this shop.
      towhom: Who would you like to transfer this shop to?
      transfered: Shop is no longer yours.
    withdraw: How much would you like to Withdraw?
  createshop:
    begin: Entering Createshop Conversation
    prefix: CREATE SHOP
    menu:
      options:
        create: create
        assign: assign
      text:
        begin: Would you like to
        create: Create a new shop.
        assign: Assign an existing shop.
    create:
      created: Shop was Created and Assigned to NPC.
      error: There was an error creating the shop.
      creating: Attempting to create shop.
  itemadmin:
    begin: Entering Item Administration
    delete:
      full: There are still some of these Items in the Inventory!
      warn: If you continue, these items will be deleted!
      confirm: Are you sure you want to delete this item?
      deleted: Item Deleted.
      cancelled: Operation Cancelled.
    prefix: ITEM ADMIN
    setprice: What would you like to CHARGE for {0}? (no or none to disable)
    setbuyprice: What would you like to PAY for {0}? (no or none to disable)
    setdescription: Give a short description of {0} (type "{1}" for no description).
    menu:
      options:
        price: sellprice
        buyprice: buyprice
        description: description
        delete: delete
        empty: empty
        exit: exit
    none: none
  setsellprice:
    prefix: SET SELL PRICE
    setprice: What would you like to charge for {0}?
  addbuyitem:
    begin: Begin adding an item to buy.
    prefix: ADD BUY ITEM
    setprice: What would you like to pay for [{0}]? (no or none to disable)
    setdescription: Give a short description. {0} (type "{1}" for no description).
    cantaddinventory: You can't add inventory in buy mode.
    added: Item Added.
    none: none
    shopfull: Shop currently is full.
  additem:
    begin: Begin adding an item for sale.
    prefix: ADD SELL ITEM
    setprice: What would you like to charge for new item [{0}]? (no or none to disable)
    setdescription: Give a short description of {0} (type "{1}" for no description).
    addinventory: Item has been added to inventory.
    added: Item Added.
    none: none
    shopfull: Shop currently is full.
  error:
    notadouble: Value needs to be a number value (2, 12.12)
    inconvo: Please exit your current conversation.
  options: Options
  toquit: (To force exit type "/quit")
debug:
  enable: Debug Enabled.
  disable: Debug Disabled.
general:
  accept: 'Yes'
  bank: Bank
  buyprice: 'Sell Price: {0}'
  buypriceview: 'Sell Price: ({0} * {1}) {2}'
  commandnotfound: Command not found.
  consoleonly: Must be a player to use this command.
  requiresubcommand: Requires a sub-command.
  decline: 'No'
  description: Description
  exit: exit
  initialized: (Shop Initialized) {0} with id {1}
  instock: Instock
  inventory: Inventory
  left: (LEFT)
  right: (RIGHT)
  name: Name
  newshopname: No Name Set.
  nocitizens: This only works with Citizens.
  notopen:
    errorloading: Store wasn't loaded properly. (Please report)
    unassigned: Store not open yet. (No store assinged)
    closed: Shop is not currently open to the public
  price: Price
  create:
    noselected: You must have an NPC selected.
    alreadytrader: NPC is already a trader.
    notowner: You need to own the NPC to create a trader.
    success: Successfully created NPC Shop.
    nopermission: You don't have permissions to create a trader NPC.
  sellprice: 'Purchase Price: {0}'
  sellpriceview: 'Purchase Price: ({0} * {1}) {2}'
  wallet:
    admin: admin
    bank: bank
    player: player
    shop: shop
permission:
  create:
    deny: You do not have permission to create a shop.
  debug:
    deny: You do not have permission to debug Ultratrader.
inventory:
  admin:
    display: Shop Admin
    lore: Click to Admin Shop
  buyadmin:
    display: Buy Admin
    lore: Click to Admin Buy Values
  itemadmin:
    display: Item Admin
    lore: Click to set Item Details
  back:
    display: Back
    lore: Click to go Back
  removestock:
    display: Remove Stock
    lore:
      full: Click to Move all to Inventory
      empty: Nothing to move to Inventory
  tocategoryscreen:
    display: Back to Categories
    lore: Goto Category Screen
  tosellscreen:
    display: Sell Screen
    lore: Goto Sell Screen
  arrange:
    display: Arrange Inventory
    lore: Click to set Inventory Arrangement.
shops:
  list:
    noshops: You don't currently own any shops.
    yourshops: 'Your current shops:'
  gotobuy:
    line1: To sell to shop
    line2: Move to Buy screen
transaction:
  sale:
    player:
      notenoughfunds: You do not have the funds for this Transaction.
    shop:
      notenoughitems: There are not enough items to purchase. (Store is out of stock)
      totalpurchase: 'Total Price: {0}'
      purchase: You bought {0} {1}
      sale: You sold {0} {1}
      notenoughfunds: Shop doesn't have the funds for this Transaction.
  error:
    economy: There was an error with the economy, please report.
    fundstoshop: There was an error, please report.